spring.application.name=backend-spring

# H2 Database Configuration
spring.datasource.url=jdbc:h2:mem:easydoc
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 Console (optional)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true

jwt.secret=${JWT_SECRET}
jwt.expiraton=${JWT_EXPIRATION:3600000}